apiVersion: apps/v1
kind: Deployment
metadata:
  name: minion-visualization
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.global.rollingUpdate.maxUnavailable | default 0 }}
  selector:
    matchLabels:
      service: minion-visualization
  template:
    metadata:
      labels:
        service: minion-visualization
    spec:
      {{- include "magda.imagePullSecrets" . | indent 6 }}
      containers:
      - name: minion-visualization
        image: {{ include "magda.image" . | quote }}
        imagePullPolicy: {{ include "magda.imagePullPolicy" . | quote }}
{{- if .Values.global.enableLivenessProbes }}
        livenessProbe:
          httpGet:
            path: "/healthz"
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 10
{{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        env:
        - name: NODE_PORT
          value: "80"
        - name: REGISTRY_URL
          value: "http://registry-api/v0"
        - name: ENABLE_MULTI_TENANTS
{{- if .Values.global.enableMultiTenants }}
          value: "true"
{{- else }}
          value: "false"
{{- end }}
        - name: TENANT_URL
          value: "http://tenant-api/v0"
        - name: USER_ID
          value: {{ .Values.global.defaultAdminUserId | default .Values.defaultAdminUserId }}
        - name: INTERNAL_URL
          value: "http://minion-visualization"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
