global:
  image: {}
  rollingUpdate: {}
  minions:
    image: {}

image: 
  name: "magda-minion-visualization"
  # repository: 
  # tag: 
  # pullPolicy: 
  # imagePullSecret: 

defaultImage:
  repository: ghcr.io/magda-io
  pullPolicy: IfNotPresent
  imagePullSecret: false

defaultAdminUserId: "00000000-0000-4000-8000-000000000000"

resources:
  requests:
    cpu: 50m
    memory: 200Mi
  limits:
    cpu: 100m